# Kafka configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Consumer configuration
    consumer:
      auto-offset-reset: earliest
      group-id: 1
    #consul service cofig
  cloud:
    consul:
      host: ${CONSULHOST:localhost}
      port: 8500
      discovery:
        enabled: true 

# Producer configuration
    



# Topics:
producerTopic: Parserbase24servicePolyTopic
consumerTopic: Base24hostParserbase24serviceTopic
base24Topic: Parserbase24serviceBase24hostTopic
