# Kafka bootstrap servers
spring:
  kafka:
    bootstrap-servers: localhost:9092

# Producer configuration
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Consumer configuration
  consumer:
    auto-offset-reset: earliest
    group-id: 1
