# Kafka configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Consumer configuration
    consumer:
      auto-offset-reset: earliest
      group-id: 1

# Topics:
producerTopic: Parserbase24servicePolyTopic
consumerTopic: Base24hostParserbase24serviceTopic
base24Topic: Parserbase24serviceBase24hostTopic
