# Kafka consumer config
spring:
  kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      consumer:
        auto-offset-reset: earliest
        group-id: 1
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            trusted:
              packages: "*"

#PostgreSQL config
  datasource:
    url: jdbc:postgresql://${POSTGES_SERVER_PORT:localhost:5432}/storage
    username: ${POSTGRES_USER:naja}
    password: ${POSTGRES_PASSWORD:naja}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
DEBUG: false
